apiVersion: apps/v1
kind: Deployment
metadata:
  name: stedi-stanley-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stedi-stanley-dev
  template:
    metadata:
      labels:
        app: stedi-stanley-dev
    spec:
      containers:
        - name: stedi-stanley-dev
          image: gcr.io/thespiders/stanley-stedi-api
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-stanley
                  key: REDIS_PASSWORD
            - name: REDIS_HOST
              value: "redis-stedi-prod"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 10
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: stedi-stanley-dev-nodeport
spec:
  selector:
    app: stedi-stanley-dev
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-stanley-dev-certificate
spec:
  domains:
    - stanley.cit262.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-stanley-ingress
  annotations:
  # gcloud compute addresses list
    kubernetes.io/ingress.global-static-ip-name: stedi-stanley-public
  # needs to match the name of the managed certificate
    networking.gke.io/managed-certificates: stedi-stanley-certificate
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
          # needs to match the name of the NodePort service
            name: stedi-stanley-dev-nodeport
            port:
              number: 80

