apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stedi-stanley
spec:
  selector:
    matchLabels:
      app: redis-stedi-stanley #must match spec.template.metadata.labels
  serviceName: redis-stedi-stanley
  replicas: 1
  template:
    metadata:
      labels:
        app:  redis-stedi-stanley
    spec:
      containers:
        - name: redis-stedi-stanley
          image: redis:7.0.5-alpine
          imagePullPolicy: Always
          args: ["--requirespass", "${REDIS_PASS}", "--apendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
              name: redis
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secrets-stanley
                key: REDIS_PASSWORD
          volumeMounts:
            - name: redis-stanley-volume
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-stanley-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-stedi-stanley
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis-stedi-stanley